### ISSUE TITLE
Is the PsyPets server down?

### ISSUE THREAD

**Issue by mariavd** [BenMakesGames/PsyPets#1]
Hi! I know that you're not maintaining PsyPets anymore but I didn't know how to get in touch with Anette. I recently came back to the game but today the server seems to be down. No response to ping. Is PsyPets dead? :(

**Comment by BenMakesGames** [comment]
I see! I can try to get in touch with Annette. we haven't talked in a long time; hopefully the info I have is still current.

also, it feels a little bit like cheating to bring this up at this moment, but I have been running a new pet game: https://poppyseedpets.com

but I'll reach out to Annette, and let you know what I find!

**Comment by mariavd** [comment]
Cool! Thanks for the quick reply. I knew about TerrePets but Poppy Seed Pets was unfamiliar. I now have a pet there, too :D I really like the style of your online games. And it's great that you also shared the code. Likely I won't ever have the time to run it on my own server but... who knows... At least PsyPets is something I fell in love with, once many years ago during high school and now thanks to the corona. The graphics are the charm of the game.

**Comment by BenMakesGames** [comment]
Annette got back to me; she is now aware of the issue!

**Comment by mariavd** [comment]
Great! Thanks!

**Comment by mariavd** [comment]
PsyPets is alive! Yay!
