### ISSUE TITLE
Security certificate expired

### ISSUE THREAD

**Issue by bauerbach** [BenMakesGames/PsyPets#2]
The certificate for PsyPets.net is expired. I can tell from another issue that you're working on another game, but an expired certificate is a major problem for websites these days I think.

**Comment by BenMakesGames** [comment]
yeah... another developer has been in charge of psypets.net for many years now. last we spoke, she had an IT guy; no idea what the situation is now, but at any rate, psypets.net is out of my hands. sorry I don't have better news!
